"""On-disk layout for the managed recipe governance overlay.

The managed overlay lives under ``<repo>/.just-for-agents/managed/``. This
module is the single source of truth for the directory tree and the only
place that materializes it on disk.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

DEFAULT_MANAGED_TOML = """# just-for-agents managed overlay configuration.
# Operators may edit this file. Keys here are read by future approval flows.

[approval]
# Self-approval is allowed in v1 (single local operator) but must still be
# recorded explicitly in history/decisions.jsonl.
allow_self_approval = true

[dry_run]
# Whether candidate recipes get an automatic dry-run on quarantine.
auto_on_quarantine = false
"""


@dataclass(frozen=True)
class ManagedPaths:
    """Resolved paths for the managed overlay rooted at ``repo_root``."""

    repo_root: Path

    @property
    def managed_root(self) -> Path:
        return self.repo_root / ".just-for-agents" / "managed"

    @property
    def config_dir(self) -> Path:
        return self.managed_root / "config"

    @property
    def config_file(self) -> Path:
        return self.config_dir / "managed.toml"

    @property
    def quarantine_dir(self) -> Path:
        return self.managed_root / "quarantine"

    @property
    def quarantine_requests_dir(self) -> Path:
        return self.quarantine_dir / "requests"

    @property
    def approved_dir(self) -> Path:
        return self.managed_root / "approved"

    @property
    def approved_recipes_dir(self) -> Path:
        return self.approved_dir / "recipes"

    @property
    def approved_includes_dir(self) -> Path:
        return self.approved_dir / "includes"

    @property
    def approved_include_file(self) -> Path:
        return self.approved_includes_dir / "managed.just"

    @property
    def rejected_requests_dir(self) -> Path:
        return self.managed_root / "rejected" / "requests"

    @property
    def history_dir(self) -> Path:
        return self.managed_root / "history"

    @property
    def decisions_log(self) -> Path:
        return self.history_dir / "decisions.jsonl"


def ensure_managed_layout(repo_root: Path) -> ManagedPaths:
    """Create the managed overlay tree if missing. Idempotent.

    Existing config files and the decisions ledger are left untouched.
    Returns the resolved :class:`ManagedPaths` for the layout.
    """

    paths = ManagedPaths(repo_root=Path(repo_root))

    for directory in (
        paths.config_dir,
        paths.quarantine_requests_dir,
        paths.approved_recipes_dir,
        paths.approved_includes_dir,
        paths.rejected_requests_dir,
        paths.history_dir,
    ):
        directory.mkdir(parents=True, exist_ok=True)

    if not paths.config_file.exists():
        paths.config_file.write_text(DEFAULT_MANAGED_TOML, encoding="utf-8")

    if not paths.approved_include_file.exists():
        paths.approved_include_file.write_text(
            "# Generated by just-for-agents managed overlay.\n"
            "# This file is rebuilt from approved/recipes/ on every approval.\n"
            "# Do not edit by hand -- direct edits are treated as drift.\n",
            encoding="utf-8",
        )

    if not paths.decisions_log.exists():
        paths.decisions_log.touch()

    return paths
