"""Generate the live projection of approved managed recipes.

The approved overlay's ``approved/recipes/<name>.just`` files are the
governed source of truth. The single live entry point into them is
``approved/includes/managed.just`` -- a generated Just include that
re-exports each approved recipe via ``import``. Quarantined requests are
intentionally absent from this file: they only come into the live surface
once their approval flow lands them under ``approved/recipes/``.

This module owns rendering and writing that include. It is the only place
that should emit content into ``approved_include_file``; every approval
flow funnels through here so the projection stays deterministic.
"""

from __future__ import annotations

from pathlib import Path

from .managed_paths import ManagedPaths

INCLUDE_HEADER = (
    "# Generated by just-for-agents managed overlay.\n"
    "# This file is rebuilt from approved/recipes/ on every approval.\n"
    "# Do not edit by hand -- direct edits are treated as drift.\n"
)


def _approved_recipe_files(paths: ManagedPaths) -> list[Path]:
    recipes_dir = paths.approved_recipes_dir
    if not recipes_dir.is_dir():
        return []
    return sorted(p for p in recipes_dir.iterdir() if p.is_file() and p.suffix == ".just")


def render_include(paths: ManagedPaths) -> str:
    """Return the deterministic contents of the approved include file."""

    lines = [INCLUDE_HEADER.rstrip("\n")]
    for recipe in _approved_recipe_files(paths):
        relative = Path("..") / "recipes" / recipe.name
        lines.append(f"# managed: {recipe.stem}")
        lines.append(f'import "{relative.as_posix()}"')
    return "\n".join(lines) + "\n"


def write_include(paths: ManagedPaths) -> Path:
    """Render and atomically write ``approved/includes/managed.just``.

    Returns the include file path. Idempotent: a second call with the same
    approved set produces the same bytes.
    """

    target = paths.approved_include_file
    target.parent.mkdir(parents=True, exist_ok=True)
    rendered = render_include(paths)

    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(rendered, encoding="utf-8")
    tmp.replace(target)
    return target
