import tempfile
import unittest
from pathlib import Path

from just_for_agents.managed_paths import ensure_managed_layout
from just_for_agents.projection import (
    INCLUDE_HEADER,
    render_include,
    write_include,
)


class RenderIncludeTests(unittest.TestCase):
    def test_empty_recipes_dir_renders_header_only(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = ensure_managed_layout(Path(tmp))
            rendered = render_include(paths)
            self.assertTrue(rendered.startswith("# Generated by just-for-agents"))
            self.assertNotIn("import ", rendered)
            self.assertTrue(rendered.endswith("\n"))

    def test_recipes_become_sorted_imports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = ensure_managed_layout(Path(tmp))
            (paths.approved_recipes_dir / "zeta.just").write_text("@zeta:\n    echo z\n")
            (paths.approved_recipes_dir / "alpha.just").write_text("@alpha:\n    echo a\n")
            (paths.approved_recipes_dir / "ignore.txt").write_text("not a recipe")

            rendered = render_include(paths)

            self.assertIn("# managed: alpha", rendered)
            self.assertIn("# managed: zeta", rendered)
            self.assertIn('import "../recipes/alpha.just"', rendered)
            self.assertIn('import "../recipes/zeta.just"', rendered)
            # alpha must come before zeta deterministically
            self.assertLess(rendered.index("alpha"), rendered.index("zeta"))
            # non-.just files are skipped
            self.assertNotIn("ignore", rendered)

    def test_write_include_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = ensure_managed_layout(Path(tmp))
            (paths.approved_recipes_dir / "foo.just").write_text("@foo:\n    echo foo\n")

            first = write_include(paths)
            self.assertEqual(first, paths.approved_include_file)
            payload_a = first.read_bytes()

            payload_b = write_include(paths).read_bytes()
            self.assertEqual(payload_a, payload_b)
            # And the rendered string matches what we wrote.
            self.assertEqual(payload_a.decode(), render_include(paths))

    def test_write_include_replaces_stale_content(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            paths = ensure_managed_layout(Path(tmp))
            paths.approved_include_file.write_text("# stale operator-edited content\n")

            (paths.approved_recipes_dir / "fresh.just").write_text("@fresh:\n    :\n")
            write_include(paths)

            content = paths.approved_include_file.read_text()
            self.assertNotIn("stale operator-edited", content)
            self.assertIn("# managed: fresh", content)
            self.assertTrue(content.startswith(INCLUDE_HEADER.rstrip("\n")))


if __name__ == "__main__":
    unittest.main()
